name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: mluzcabrera/testGHreusableworkflows/.github/workflows/reusable.yml
    with:
      environment: prod

  job2:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo ${{ vars.avar }} ${{ secrets.asecret }}
