name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test-access-secret-in-env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo ${{ secrets.asecret }} 
  test-access-secret-in-context:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.asecret }} 
